name: "Alfred Workflow Release Creator"

on:
  push

env:
  WORKFLOW_FILE: "AppStorrent.alfredworkflow"
  CHANGELOG_FILE: CHANGELOG.md
  REPO:  ${{ github.repository }}
  SHA: ${{ github.sha }}
  EMAIL: jag-k58@ya.ru
  LOGIN: jag-k

jobs:
  create-release:
    name: "Create Release"
    runs-on: macos-latest

    steps:
      - name: "Clone Repo"
        uses: actions/checkout@v2.3.0

      - name: "Set up Python 2.7"
        uses: actions/setup-python@v2
        with:
          python-version: 2.7

      - name: "Create `${{ env.WORKFLOW_FILE }}`"
        run: |
          python build.py

      - name: "Upload a Build Artifact"
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.WORKFLOW_FILE }}
          path: ${{ env.WORKFLOW_FILE }}

      - uses: mukunku/tag-exists-action@v1.0.0
        id: checkTag
        with:
          tag: ${{ env.TAG }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: "Add Release in ${{ env.CHANGELOG_FILE }}"
        if: ${{ steps.checkTag.outputs.exists == 'false' }}
        run: |
          python changelog_control.py ${{ env.TAG }}

      - name: "Git Commit and Push"
        if: ${{ env.CHANGED_CHANGELOG == 'true' && steps.checkTag.outputs.exists == 'false' }}
        run: |
          git config user.email ${{ env.EMAIL }}
          git config user.name ${{ env.LOGIN }}
          {
            git add ${{ env.CHANGELOG_FILE }}
            git commit -m ":octocat: GitHub Actions Release"
            git push
          } || {
            echo "Nothing to commit"
          }

      - name: "Create a Release"
        uses: softprops/action-gh-release@v1
        if: ${{ steps.checkTag.outputs.exists == 'false' }}
        with:
          tag_name: ${{ env.TAG }}
          name: "Release ${{ env.TAG }}"
          files: ${{ env.WORKFLOW_FILE }}
          body_path: release.txt
          draft: false
          prerelease: ${{ env.PRERELEASE == 'true' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}